# Generated by Django 4.2.2 on 2023-07-15 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_escambo', '0004_produto_destaque_alter_escambador_foto_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='escambo',
            old_name='status_escambo',
            new_name='escambo_ativo',
        ),
        migrations.AddField(
            model_name='produto',
            name='status_trocado',
            field=models.BooleanField(default=False),
        ),
    ]
