# Generated by Django 4.2.2 on 2023-07-15 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_escambo', '0005_rename_status_escambo_escambo_escambo_ativo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='escambador',
            name='ativos',
            field=models.IntegerField(default=0),
        ),
    ]
