# Generated by Django 4.2.2 on 2023-07-16 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_escambo', '0006_escambador_ativos'),
    ]

    operations = [
        migrations.AddField(
            model_name='escambo',
            name='confirmado_usuario1',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='escambo',
            name='confirmado_usuario2',
            field=models.BooleanField(default=False),
        ),
    ]
