# Generated by Django 4.2.2 on 2023-06-21 20:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_escambo', '0007_termos_status_termo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='escambador',
            name='termos',
        ),
        migrations.DeleteModel(
            name='Termos',
        ),
    ]
