# Generated by Django 4.2.3 on 2023-07-06 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_escambo', '0007_termos_status_termo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='escambador',
            name='endereco',
            field=models.CharField(max_length=255, verbose_name='Endereço'),
        ),
    ]
