# Generated by Django 4.2.2 on 2023-06-17 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_escambo', '0006_termos_rename_troca_escambo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='termos',
            name='status_termo',
            field=models.BooleanField(default=False),
        ),
    ]
